(load "common.scm")

;; The corporate CloudFlare TLS-inspection proxy re-signs some hosts (e.g. the
;; Azure blob storage that GitHub artifact downloads redirect to) with a private
;; CA. gh (Go) and other tools obey SSL_CERT_FILE and ignore the system
;; /etc/ssl/certs, so fold that CA into the bundle we point SSL_CERT_FILE at.
;; nss-certs ships individual PEMs (the single bundle is a profile hook), so
;; concatenate every *.pem plus the corp cert. The corp cert is read from the
;; system store at reconfigure time -- it is not committed to this repo.
(define %ca-certificates-with-corp
  (let ((corp-cert
         (local-file "/etc/ssl/certs/Sonar-CloudFlare-Inspection-Cert.pem")))
    (computed-file
     "ca-certificates-with-corp.crt"
     #~(begin
         (use-modules (ice-9 ftw)
                      (ice-9 textual-ports)
                      (srfi srfi-13))
         (define (append-file out f)
           (call-with-input-file f
             (lambda (in)
               (put-string out (get-string-all in))
               (put-char out #\newline))))
         (let ((certs-dir (string-append #$nss-certs "/etc/ssl/certs")))
           (call-with-output-file #$output
             (lambda (out)
               (for-each
                (lambda (name)
                  (append-file out (string-append certs-dir "/" name)))
                (sort (scandir certs-dir
                               (lambda (n) (string-suffix? ".pem" n)))
                      string<?))
               (append-file out #$corp-cert))))))))

;; Gradle reads exactly one user-level properties file, $GRADLE_USER_HOME/gradle.properties.
;; It merges no second file, and an init.d script cannot supply Gradle properties either
;; (they are finalised before init scripts run). So assemble that one file at activation
;; time out of two fragments, the later one winning:
;;   config/gradle.properties          -- shared defaults (tracked)
;;   ~/.cache/secrets/gradle.properties -- credentials (untracked, never in this repo)
;; The second one is why this is generated rather than a store symlink: repository
;; credentials must not live in a public dotfiles repo. It is read at activation time
;; and is optional, so a machine without it still reconfigures.
(define %gradle-config-service
  (let ((shared (local-file (string-append %guix-config-dir "/gradle.properties")))
        (secrets (string-append %home "/.cache/secrets/gradle.properties"))
        (target (string-append %home "/.config/gradle/gradle.properties")))
    (simple-service
     'gradle-config
     home-activation-service-type
     #~(begin
         (use-modules (ice-9 textual-ports))
         (let* ((target #$target)
                (dir (dirname target))
                (secrets #$secrets)
                (fragments (append (list #$shared)
                                   (if (file-exists? secrets) (list secrets) '()))))
           (unless (file-exists? dir) (mkdir dir))
           ;; No home-files service may declare this path, or the symlink pass would
           ;; fight the file we write here.
           (call-with-output-file target
             (lambda (out)
               (display "# Generated by `guix home reconfigure' -- do not edit.\n" out)
               (for-each (lambda (f)
                           (display (call-with-input-file f get-string-all) out)
                           (newline out))
                         fragments)))
           (chmod target #o600))))))

(home-env "professional" '("/home/arseniy/.sonar/bin/")
          #:ssl-cert-file %ca-certificates-with-corp
          #:gradle-config-service %gradle-config-service)
