#!/bin/bash

# Run the second screen in extended mode, instead of the default mirror
. ~/.xmonad/other-screen-on.sh

trayer --edge bottom --align left --SetDockType true --SetPartialStrut true \
       --expand true --widthtype pixel --width 180 --transparent true \
       --tint 0x191970 --heighttype pixel --height 33 --monitor primary \
       --distance 0 --distancefrom bottom &

xsetroot -solid midnightblue
xsetroot -cursor_name left_ptr
if [ -x /usr/lib/gnome-settings-daemon/gsd-xsettings ]; then
    # make sure the interface fonts and magnification factors are applied
    /usr/lib/gnome-settings-daemon/gsd-xsettings &
fi

# Set background image with feh
feh --bg-scale /usr/share/backgrounds/singularity.jpg &

if [ -x /usr/bin/nm-applet ] ; then
    # network manager applet into the systray
    nm-applet --sm-disable &
fi

if [ -x /usr/bin/gnome-keyring-daemon ]; then
    # This combines ssh-agent and gpg-agent for key management.
    # $(...) sources the command output to set variables.
    export $(gnome-keyring-daemon --start --daemonize)
fi

export PATH=$PATH:/opt/cisco/anyconnect/bin
export SHELL=bash

exec xmonad
