#!/bin/bash

trayer --edge bottom --align left --SetDockType true --SetPartialStrut true \
       --expand true --widthtype pixel --width 180 --transparent true \
       --tint 0x191970 --heighttype pixel --height 33 --monitor primary \
       --distance 0 --distancefrom bottom &

xsetroot -solid midnightblue
xsetroot -cursor_name left_ptr
/usr/lib/gnome-settings-daemon/gsd-xsettings &

#eval $(gnome-settings-daemon)
#eval $(gnome-keyring-daemon --start)
#export GNOME_KEYRING_SOCKET
#export GNOME_KEYRING_PID

# Set background image with feh
feh --bg-scale /usr/share/backgrounds/singularity.jpg &

#dropbox start &

if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi

export PATH=$PATH:/opt/cisco/anyconnect/bin
export SHELL=bash

exec xmonad
