#!/bin/bash

trayer --edge top --align right --SetDockType true --SetPartialStrut true \
       --expand true --width 7 --transparent true --tint 0x191970 --height 33 &

xsetroot -solid midnightblue

#eval $(gnome-settings-daemon)
#eval $(gnome-keyring-daemon --start)
#export GNOME_KEYRING_SOCKET
#export GNOME_KEYRING_PID

# Set background image with feh
feh --bg-scale /usr/share/backgrounds/singularity.jpg &

#dropbox start &

if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi

export PATH=$PATH:/opt/cisco/anyconnect/bin
export SHELL=bash

exec xmonad
